### Hanan Sherka 
### Lab 4/Data Cleaning
### Sconyers, Pr. 2
### October 3rd, 2018

## Introduction

    In this lab, we are taking three raw data sets and cleaning them to the best of our ability, and indicating what more we would like to do to better clean the data if we had the time and/or the coding skill. We are not cleaning the data to serve a specific purpose, or to do any statistical analysis; instead, we are just practicing our data cleaning skills and learning code to best do so. There are three data sets: the first, is the Boing Boing data set, which is one on candy. The second, is a dataset that is about the average percent of attendance at public schools, categorized by state. The last dataset is data on ticket sales for national U.S. events.

## Dataset Preparation

In [258]:
#always include aliased packages
import math as m 
import numpy as np
import scipy as sp 
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt 
import seaborn as sns

### Candy Data

In [259]:
# One line to open and read an excel file into a data frame data structure, make the first row the header,
# then close the file. 
df = pd.read_excel('BOING-BOING-CANDY-HIERARCHY-2016-SURVEY-Responses.xlsx', encoding = "ISO-8859-1")

# Print the first couple of lines to ensure that everything is correct
df.head()

,Timestamp,Are you going actually going trick or treating yourself?,Your gender:,How old are you?,Which country do you live in?,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
0,2016-10-24 05:09:23.033,No,Male,22,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN
1,2016-10-24 05:09:54.798,No,Male,45,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
2,2016-10-24 05:13:06.734,No,Female,48,US,Colorado,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
3,2016-10-24 05:14:17.192,No,Male,57,usa,il,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN
4,2016-10-24 05:14:24.625,Yes,Male,42,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN

In [260]:
# Dropping the last column because by looking at the metadata (the original survey) this last row is not an
# actual survey question
df.drop(' [York Peppermint Patties] Ignore', axis = 1, inplace = True)

# Printing the info to see if there is one less column now that I have dropped one. We started with 123, 
# so now we should (and do) have 122
df.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Columns: 122 entries, Timestamp to When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).
dtypes: datetime64[ns](1), object(121)
memory usage: 1.2+ MB

In [261]:
# The next thing I wanted to do was to rename the headers, because they are excessively wordy, and don't always make sense. 
# Because I didn't have time to do every one (there are over 100), I did so with just the first five. If I had more time,
# I would do all of them

df.rename(columns = {
    'Timestamp' : 'Time' ,
    'Are you going actually going trick or treating yourself?' : 'ToT?' ,
    'Your gender:' : 'Gender' ,
    'How old are you?' :'Age' ,
    'Which country do you live in?' : 'Country' , 
    },  inplace = True )

In [262]:
# I noticed inconsistensies and incorrect spellings of countries. For example usa vs US vs USA. All of these be 
# recognized as different countries even though they are all the same. I made the entire country column lowercase so that 
# would eliminate one difference. 
df["Country"] = df["Country"].str.lower()
df.head ()

,Time,ToT?,Gender,Age,Country,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,What is your favourite font?,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest)."
0,2016-10-24 05:09:23.033,No,Male,22,canada,Ontario,JOY,DESPAIR,JOY,MEH,...,impact,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines
1,2016-10-24 05:09:54.798,No,Male,45,usa,il,MEH,MEH,JOY,JOY,...,Calibri,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines
2,2016-10-24 05:13:06.734,No,Female,48,us,Colorado,JOY,DESPAIR,JOY,MEH,...,garamond,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines
3,2016-10-24 05:14:17.192,No,Male,57,usa,il,JOY,MEH,JOY,MEH,...,Papyrus,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines
4,2016-10-24 05:14:24.625,Yes,Male,42,usa,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,Default,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN

In [263]:
#Then I took a couple of variations of USA to all become the same. If I had more time, 
# I would apply this to every country that had this issue, and address every variation. 
df.replace(to_replace = "us", value = "usa", inplace = True)

df.head ()
# Now, the first four "usa" entries are all the same. By changing the case and replacing us to usa.

,Time,ToT?,Gender,Age,Country,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,What is your favourite font?,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest)."
0,2016-10-24 05:09:23.033,No,Male,22,canada,Ontario,JOY,DESPAIR,JOY,MEH,...,impact,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines
1,2016-10-24 05:09:54.798,No,Male,45,usa,il,MEH,MEH,JOY,JOY,...,Calibri,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines
2,2016-10-24 05:13:06.734,No,Female,48,usa,Colorado,JOY,DESPAIR,JOY,MEH,...,garamond,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines
3,2016-10-24 05:14:17.192,No,Male,57,usa,il,JOY,MEH,JOY,MEH,...,Papyrus,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines
4,2016-10-24 05:14:24.625,Yes,Male,42,usa,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,Default,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN

In [264]:
# I found that the columns with open ended questions had data that was not sortable because the surveyed people 
# could enter whatever they wanted. This made me think that they were not worth keeping, so I deleted age. This is because
# for age, they did not have to select their age, but could type out whatever they wanted. There were a lot of answers that 
# were not numbers. 

df.drop('Age', axis = 1, inplace = True)
df.head()

,Time,ToT?,Gender,Country,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],[Bonkers (the candy)],...,What is your favourite font?,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest)."
0,2016-10-24 05:09:23.033,No,Male,canada,Ontario,JOY,DESPAIR,JOY,MEH,MEH,...,impact,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines
1,2016-10-24 05:09:54.798,No,Male,usa,il,MEH,MEH,JOY,JOY,DESPAIR,...,Calibri,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines
2,2016-10-24 05:13:06.734,No,Female,usa,Colorado,JOY,DESPAIR,JOY,MEH,MEH,...,garamond,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines
3,2016-10-24 05:14:17.192,No,Male,usa,il,JOY,MEH,JOY,MEH,MEH,...,Papyrus,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines
4,2016-10-24 05:14:24.625,Yes,Male,usa,South Dakota,MEH,DESPAIR,JOY,DESPAIR,MEH,...,Default,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN

In [265]:
# Lastly for this dataset, I decided that if there was a blank in one of the columns that allowed someone to rate a candy, 
# I would replace it with "undecided". This would show that there were unanswered pieces of that question, but would not 
# disturb the data for the people who answered. It would make it clear how many people didn't answer it for whatever reason
# I only did this for one column, the [100 Grand Bar] column, but if I had time I'd do it for all of them

df.replace(to_replace = "", value = "undecided", inplace = True)

df.head()

,Time,ToT?,Gender,Country,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],[Bonkers (the candy)],...,What is your favourite font?,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest)."
0,2016-10-24 05:09:23.033,No,Male,canada,Ontario,JOY,DESPAIR,JOY,MEH,MEH,...,impact,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines
1,2016-10-24 05:09:54.798,No,Male,usa,il,MEH,MEH,JOY,JOY,DESPAIR,...,Calibri,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines
2,2016-10-24 05:13:06.734,No,Female,usa,Colorado,JOY,DESPAIR,JOY,MEH,MEH,...,garamond,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines
3,2016-10-24 05:14:17.192,No,Male,usa,il,JOY,MEH,JOY,MEH,MEH,...,Papyrus,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines
4,2016-10-24 05:14:24.625,Yes,Male,usa,South Dakota,MEH,DESPAIR,JOY,DESPAIR,MEH,...,Default,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN

### Attendance Data

In [266]:
# Changed every header name so that it was clear/understandable for me, removed the multiple headerrows, and displayed to ensure
# it was working correctly. Opened and read an excel file into a data frame data structure, then closed it. 

headern = ["states", "combined_ada", "combined_ada2", "combined_hours", "combined_hours2", "combined_days_in_year", 
              "combined_days_in_year2", "combined_hours_in_year","combined_hours_in_year2", "elementary_ada", 
              "elementary_ada2", "elementary_hours_in_day", "elementary_hours_in_day2",
               "secondary_ada", "secondary_ada2", "secondary_hours_in_a_day", "secondary_hours_in_a_day2"]

df2 = pd.read_excel("attendance.xls", skiprows=3, names=headern)

df2.head()

,states,combined_ada,combined_ada2,combined_hours,combined_hours2,combined_days_in_year,combined_days_in_year2,combined_hours_in_year,combined_hours_in_year2,elementary_ada,elementary_ada2,elementary_hours_in_day,elementary_hours_in_day2,secondary_ada,secondary_ada2,secondary_hours_in_a_day,secondary_hours_in_a_day2
0,United States ........,93.078962,0.218555,6.64470,0.017650,180.0,0.142993,1192.6472,3.0859,94.004983,0.269369,6.656056,0.015998,91.1181,0.432223,6.59439,0.040308
1,Alabama .................,93.812371,1.237261,7.02852,0.065621,180.0,0.755110,1266.6205,12.3343,93.776375,1.839154,7.038473,0.075944,94.561,0.37928,7.13724,0.17312
2,Alaska ..................,89.917597,1.215976,6.47688,0.049882,180.0,3.427735,1162.9084,22.8639,91.281537,1.563482,6.486785,0.053082,93.2409,1.57371,6.24087,0.145993
3,Arizona .................,89.036961,2.952601,6.43369,0.091917,181.0,1.678664,1159.1144,14.4327,88.904393,3.905033,6.443155,0.102053,88.9797,3.22058,6.36909,0.248824
4,Arkansas ................,91.827111,1.352924,6.88542,0.061468,179.0,0.201577,1228.8881,10.6821,92.093201,2.091651,6.932160,0.076546,90.812,2.23155,6.76751,0.095928

In [267]:
# Dropped rows 66 - 69 (this is the index on the excel file, which is why the code doesnot match up with these numbers)
# because they are index rows and not actual data values. Checked info before and after to ensure that 
# the number of rows decreased 
df2.drop(df2.index[[61,62,63,64]], inplace = True )

In [268]:
# I then dropped the empty rows that were in betweeen states and empty for no reason 
df2.drop(df2.index[[6, 12, 18, 24, 30, 36, 42, 48]], inplace = True )

In [269]:
# I then wanted to fill all empty or valueless points. From the index I found that ‡ means insufficient data and † means
# not applicable. So I replaced these with those words so someone analyzing the data can easily understand without
# having to look at an index
df2.replace(to_replace = "†", value = "not applicable", inplace = True)
df2.replace(to_replace = "‡", value = "insufficient data", inplace = True)
df2.replace(to_replace = "(†)", value = "not applicable", inplace = True)
df2.replace(to_replace = "(‡)", value = "insufficient data", inplace = True)

# I printed Deleware's row to make sure that it replaced the right symbols with the right strings I wanted. 
print(df2.loc[[9]])

                      states  combined_ada  combined_ada2  combined_hours  \
9  Delaware ................     89.770581       1.754942         6.67801

   combined_hours2  combined_days_in_year  combined_days_in_year2  \
9         0.089584                  181.0                0.831973

   combined_hours_in_year  combined_hours_in_year2  elementary_ada  \
9               1208.2303                  18.6503       89.363391

   elementary_ada2  elementary_hours_in_day  elementary_hours_in_day2  \
9         2.502472                 6.766382                  0.060578

       secondary_ada  secondary_ada2 secondary_hours_in_a_day  \
9  insufficient data  not applicable                  6.54407

  secondary_hours_in_a_day2
9                  0.225909

### Sales Data

In [270]:
# One line to open and read an excel file into a data frame data structure, make the first row the header,
# then close the file. 
df3 = pd.read_csv("sales (1).csv",  encoding = "ISO-8859-1")

df3.head()

,Unnamed: 0,event_id,primary_act_id,secondary_act_id,purch_party_lkup_id,event_name,primary_act_name,secondary_act_name,major_cat_name,minor_cat_name,...,edu_1st_indv_val,edu_2nd_indv_val,adults_in_hh_num,married_ind,child_present_ind,home_owner_ind,occpn_val,occpn_1st_val,occpn_2nd_val,dist_to_ven
0,1,abcaf1adb99a935fc661,43f0436b905bfa7c2eec,b85143bf51323b72e53c,7dfa56dd7d5956b17587,Xfinity Center Mansfield Premier Parking: Flor...,XFINITY Center Mansfield Premier Parking,NaN,MISC,PARKING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,6c56d7f08c95f2aa453c,1a3e9aecd0617706a794,f53529c5679ea6ca5a48,4f9e6fc637eaf7b736c2,Gorge Camping - dave matthews band - sept 3-7,Gorge Camping,Dave Matthews Band,MISC,CAMPING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0
2,3,c7ab4524a121f9d687d2,4b677c3f5bec71eec8d1,b85143bf51323b72e53c,6c2545703bd527a7144d,Dodge Theatre Adams Street Parking - benise,Parking Event,NaN,MISC,PARKING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,394cb493f893be9b9ed1,b1ccea01ad6ef8522796,b85143bf51323b72e53c,527d6b1eaffc69ddd882,Gexa Energy Pavilion Vip Parking : kid rock wi...,Gexa Energy Pavilion VIP Parking,NaN,MISC,PARKING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,55b5f67e618557929f48,91c03a34b562436efa3c,b85143bf51323b72e53c,8bd62c394a35213bdf52,Premier Parking - motley crue,White River Amphitheatre Premier Parking,NaN,MISC,PARKING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [271]:
# I deleted the different event identification columns so that instead of using these weird long numbers, someone could 
# either just use the index, or the event name to focus in on that row of data. I also deleted the numbered index, because you 
# can call for a row without that number there. 
df3.drop("Unnamed: 0", axis = 1, inplace = True)
df3.drop("event_id", axis = 1, inplace = True) 
df3.drop("primary_act_id", axis = 1, inplace = True) 
df3.drop("secondary_act_id", axis = 1, inplace = True) 
df3.drop("purch_party_lkup_id", axis = 1, inplace = True) 

df3.head()

,event_name,primary_act_name,secondary_act_name,major_cat_name,minor_cat_name,la_event_type_cat,event_disp_name,ticket_text,tickets_purchased_qty,trans_face_val_amt,...,edu_1st_indv_val,edu_2nd_indv_val,adults_in_hh_num,married_ind,child_present_ind,home_owner_ind,occpn_val,occpn_1st_val,occpn_2nd_val,dist_to_ven
0,Xfinity Center Mansfield Premier Parking: Flor...,XFINITY Center Mansfield Premier Parking,NaN,MISC,PARKING,PARKING,Xfinity Center Mansfield Premier Parking: Flor...,THIS TICKET IS VALID FOR PARKING ONL...,1,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Gorge Camping - dave matthews band - sept 3-7,Gorge Camping,Dave Matthews Band,MISC,CAMPING,INVALID,Gorge Camping - dave matthews band - sept 3-7,%OVERNIGHT C A M P I N G%* * * * * *%GORGE CAM...,1,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0
2,Dodge Theatre Adams Street Parking - benise,Parking Event,NaN,MISC,PARKING,PARKING,Dodge Theatre Adams Street Parking - benise,ADAMS STREET GARAGE%PARKING FOR 4/21/06 ONLY%D...,1,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Gexa Energy Pavilion Vip Parking : kid rock wi...,Gexa Energy Pavilion VIP Parking,NaN,MISC,PARKING,PARKING,Gexa Energy Pavilion Vip Parking : kid rock wi...,THIS TICKET IS VALID FOR PARKING ONL...,1,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Premier Parking - motley crue,White River Amphitheatre Premier Parking,NaN,MISC,PARKING,PARKING,Premier Parking - motley crue,THIS TICKET IS VALID%FOR PARKING ONLY%GOOD THI...,1,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Conclusion

    This lab made me realize how much work data cleaning is, and how to is very dependant upon what analysis one wants to pull from the data, so that the cleaning is focused on the needs of the analysist/person using the data. For the first data set, I was not able to apply every data cleaning part to all the data. One thing I would have liked to do, but did not have the coding knowledge to do, is to find out how many NaN values are in a column, and if there are more than 20% Nan values, that column is deleted. This way insufficient data is removed.
    For the second dataset, I wish I could know how to delete all blank rows in one line of code. I would have also wished I could remove the parentheses in some of the data values, so it can all be uniform. 
    Finally, for the last dataset, I wish I had more metadata so that by better understanding what each column is for, I would know what to omit, and what to change.

## Acknowldegments

    I used the "Lillian's Question" file for code to replace headers for the first dataset. For the second dataset, I recieved code from Ms. Sconyers for the header replacement for the second dataset. I also mirrored some of the pandas code through the Data-Cleaning-101. I also revieved the encoding number from Ms. Sconyers to be able to read the files.